//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_TEMPSENSOR_H
#define RIAPS_CORE_TEMPSENSOR_H

#include "componentmodel/r_componentbase.h"
#include "TempDatatype.capnp.h"

// Name of the ports from the model file
#define PORT_TIMER_CLOCK "clock"
#define PORT_PUB_READY "ready"

namespace weathermonitor {
   namespace components {
      
      class TempSensorBase : public riaps::ComponentBase {
         
         public:
         TempSensorBase(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnClock(riaps::ports::PortBase *port)=0;
         
         virtual bool SendReady(capnp::MallocMessageBuilder& messageBuilder,
         TempDatatype::Builder& message);
         
         virtual ~TempSensorBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_TEMPSENSOR_H
