//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//

#ifndef RIAPS_CORE_TEMPMONITOR_H
#define RIAPS_CORE_TEMPMONITOR_H

#include "componentmodel/r_componentbase.h"
#include "TempDatatype.capnp.h"

// Name of the ports from the model file
#define PORT_SUB_TEMPUPDATE "tempupdate"

namespace weathermonitor {
   namespace components {
      
      class TempMonitorBase : public riaps::ComponentBase {
         
         public:
         TempMonitorBase(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnTempupdate (const TempDatatype::Reader &message,
         riaps::ports::PortBase *port)=0;
         
         virtual ~TempMonitorBase();
         protected:
         virtual void DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params=nullptr );
         virtual void DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port);
      };
   }
}
#endif //RIAPS_CORE_TEMPMONITOR_H
