//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_TEMPMONITOR_H
#define RIAPS_FW_TEMPMONITOR_H

#include "TempMonitorBase.h"

namespace weathermonitor {
   namespace components {
      
      class TempMonitor : public TempMonitorBase {
         
         public:
         
         TempMonitor(_component_conf &config, riaps::Actor &actor);
         
         virtual void OnTempupdate(const TempDatatype::Reader &message,
         riaps::ports::PortBase *port);
         
         void OnGroupMessage(const riaps::groups::GroupId& groupId, capnp::FlatArrayMessageReader& capnpreader, riaps::ports::PortBase* port);
         
         virtual ~TempMonitor();
         
      };
   }
}

extern "C" riaps::ComponentBase* create_component(_component_conf&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_TEMPMONITOR_H
