#!/bin/sh
#Script to start services that are needed before running an actor
#Created on Dec 8, 2016

#Arguments:
# redis server configuration file
# --database DatabaseLocation
# DatabaseLocation is a string used to contact the shared database used to store and lookup port registrations.
# For redis, it is hostName:portNumber pair

#@author: riaps

redis-server ~/.local/riaps/etc/redis.conf &
~/.local/bin/riaps_disco --database localhost:6379 &

