#!/usr/bin/python3
'''
Script to test app log config file

Created on Oct 20, 2022

Arguments
-f (or --file) FILE : Path to the file that will be used to construct the loggers
@author: riaps
'''

import argparse
import time
import riaps.utils.spdlog_setup as spdlog_setup


def test_loggers(loggers, msg):
    for logger in loggers:
        print(f"logger: {logger}")
        loggers[logger].info(msg)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-F", "--file", default="riaps-log.conf")
    args = parser.parse_args()
    print(args)

    loggers = spdlog_setup.from_file(args.file)
    for i in range(10):
        test_loggers(loggers, f"message: {i}")
        time.sleep(1)


