#!/usr/bin/python3
'''

Script to generate a public/private key pair and a
self-signed certificate for securing riaps communications.
THE KEY ANND CERTIFICATE MUST NEVER BE USED IN FIELDED SYSTEMS.
Keys and the certificate must be installed in the $RIAPSHOME/keys
directory. Private key is NOT ENCRYPTED.
 
@author: riaps
'''
from riaps.utils.gencert import main

if __name__ == '__main__':
    main()
