//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#include <TempMonitorBase.h>

namespace weathermonitor {
   namespace components {
      
      TempMonitorBase::TempMonitorBase(_component_conf &config, riaps::Actor &actor) : ComponentBase(config, actor) {
         
      }
      
      void TempMonitorBase::DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params) {
         auto portName = port->GetPortName();
         if (portName == PORT_SUB_TEMPUPDATE) {
            TempDatatype::Reader Tempupdate =
            capnpreader->getRoot<TempDatatype>();
            OnTempupdate(Tempupdate, port);
         }
         
      }
      
      void TempMonitorBase::DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port) {
         //empty the header
      }
      
      
      TempMonitorBase::~TempMonitorBase() {
         
      }
   }
}
