//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#include <TempSensorBase.h>

namespace weathermonitor {
   namespace components {
      
      TempSensorBase::TempSensorBase(_component_conf &config, riaps::Actor &actor) : ComponentBase(config, actor) {
         
      }
      
      void TempSensorBase::DispatchMessage(capnp::FlatArrayMessageReader* capnpreader, riaps::ports::PortBase *port,std::shared_ptr<riaps::MessageParams> params) {
         auto portName = port->GetPortName();
         if (portName == PORT_TIMER_CLOCK) {
            OnClock(port);
         }
         
         
      }
      
      void TempSensorBase::DispatchInsideMessage(zmsg_t* zmsg, riaps::ports::PortBase* port) {
         //empty the header
      }
      
      bool TempSensorBase::SendReady(capnp::MallocMessageBuilder &messageBuilder,
      TempDatatype::Builder &message) {
         std::cout<< "TempSensorBase::SendReady()"<< std::endl;
         return SendMessageOnPort(messageBuilder, PORT_PUB_READY);
      }
      
      TempSensorBase::~TempSensorBase() {
         
      }
   }
}
