/*
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.tests

import com.google.inject.Inject
import edu.vanderbilt.riaps.datatypes.Mdodel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DatatypesInjectorProvider)
class DatatypesParsingTest{

	@Inject
	ParseHelper<Mdodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext! 
		''')
		Assert.assertNotNull(result)
	}

}
