#!/bin/bash

PYCOM_ETC_DIR="/etc/riaps"
PYCOM_LN_DIR="/usr/local/riaps"

# Remove security keys (including soft links)
rm -f $PYCOM_ETC_DIR/id_rsa.pub  $PYCOM_ETC_DIR/id_rsa.key || true
rm -f $PYCOM_ETC_DIR/riaps-sys.cert  $PYCOM_ETC_DIR/x509.pem || true
rm -f $PYCOM_LN_DIR/keys/id_rsa.pub $PYCOM_LN_DIR/keys/id_rsa.key || true
rm -f $PYCOM_LN_DIR/keys/riaps-sys.cert $PYCOM_LN_DIR/keys/x509.pem || true

# Remove soft links to conffiles
rm -f $PYCOM_LN_DIR/etc/riaps.conf  $PYCOM_LN_DIR/etc/riaps-log.conf || true
rm -f $PYCOM_LN_DIR/etc/redis.conf || true
rm -f $PYCOM_LN_DIR/etc/riaps-hosts.conf $PYCOM_LN_DIR/etc/riaps-ctrl.glade || true

# Uninstall riaps-pycom package
pip3 uninstall -y riaps-pycom || true

# Remove apparmor file from the cache
rm -f /etc/apparmor.d/cache/usr.local.bin.riaps_actor || true

sudo mv /etc/environment.bak /etc/environment

systemctl daemon-reload
