#!/bin/bash
set -e

# Note: Specific for developer package
ln -s /etc/riaps/riaps-hosts.conf /usr/local/riaps/etc/riaps-hosts.conf
ln -s /etc/riaps/riaps-ctrl.glade /usr/local/riaps/etc/riaps-ctrl.glade

# Enable and start RIAPS services
systemctl enable riaps-rpyc-registry.service
systemctl start riaps-rpyc-registry.service || true
# Disable riaps-deplo.service for the controller 
systemctl stop riaps-deplo.service
systemctl disable riaps-deplo.service || true
