#!/bin/bash

# Remove security keys (including soft links)
rm -f /etc/riaps/id_rsa.pub  /etc/riaps/id_rsa.key || true
rm -f /etc/riaps/riaps-sys.cert  /etc/riaps/x509.pem || true
rm -f /usr/local/riaps/keys/id_rsa.pub /usr/local/riaps/keys/id_rsa.key || true
rm -f /usr/local/riaps/keys/riaps-sys.cert /usr/local/riaps/keys/x509.pem || true

# Remove soft links to conffiles
rm -f /usr/local/riaps/etc/riaps.conf  /usr/local/riaps/etc/riaps-log.conf || true
rm -f /usr/local/riaps/etc/redis.conf || true
rm -f /usr/local/riaps/etc/riaps-hosts.conf /usr/local/riaps/etc/riaps-ctrl.glade || true

# Uninstall riaps-pycom package
pip3 uninstall -y riaps-pycom-dev || true

# Remove apparmor file from the cache
rm -f /etc/apparmor.d/cache/usr.local.bin.riaps_actor || true

systemctl daemon-reload
