#!/bin/bash

# Stop and remove RIAPS services
systemctl stop riaps-rm-cgroups.service || true
systemctl disable riaps-rm-cgroups.service
systemctl stop riaps-rm-quota.service || true
systemctl disable riaps-rm-quota.service
# Note: Normal RIAPS nodes have riaps-deplo active on boot
systemctl stop riaps-deplo.service || true
systemctl disable riaps-deplo.service

# Save off security keys for use with next install
mkdir -p /tmp/riaps-pycom-save/
echo "Saving existing security keys (/tmp/riaps-pycom-save/)"
sudo cp /etc/riaps/id_rsa.key /tmp/riaps-pycom-save/id_rsa.key
sudo cp /etc/riaps/id_rsa.pub /tmp/riaps-pycom-save/id_rsa.pub
sudo cp /etc/riaps/riaps-sys.cert /tmp/riaps-pycom-save/riaps-sys.cert
sudo cp /etc/riaps/x509.pem /tmp/riaps-pycom-save/x509.pem
