#!/bin/bash

# Stop and remove RIAPS services
systemctl stop riaps-apparmor-pyversion.service
systemctl disable riaps-apparmor-pyversion.service || true
systemctl stop riaps-rm-cgroups.service || true
systemctl disable riaps-rm-cgroups.service
systemctl stop riaps-rm-quota.service || true
systemctl disable riaps-rm-quota.service
# Note: Normal RIAPS nodes have riaps-deplo active on boot
systemctl stop riaps-deplo.service || true
systemctl disable riaps-deplo.service

# Save off security keys for use with next install
SAVE_KEYS_PATH="/home/riaps/.ssh/riaps-pycom-save"
PYCOM_ETC_DIR="/etc/riaps"
mkdir -p $SAVE_KEYS_PATH
echo "Saving existing security keys ($SAVE_KEYS_PATH)"
sudo cp $PYCOM_ETC_DIR/id_rsa.key $SAVE_KEYS_PATH/id_rsa.key
sudo cp $PYCOM_ETC_DIR/id_rsa.pub $SAVE_KEYS_PATH/id_rsa.pub
sudo cp $PYCOM_ETC_DIR/riaps-sys.cert $SAVE_KEYS_PATH/riaps-sys.cert
sudo cp $PYCOM_ETC_DIR/x509.pem $SAVE_KEYS_PATH/x509.pem
