@0xc2124bee9f5225e7; # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("modbus::messages");

struct DeviceQry{
    # device is the name of a device from the device yaml file
    # operation is "READ" or "WRITE"
    # param is the parameter of interest from from the device yaml file
    # value is what is written when performing a WRITE operation
    device @0: Text;
    operation @1: Text;
    param @2: List(Text);
    value @3: List(Float64) = [0];
    timestamp @4: Float64;
}

struct DeviceAns {
    reply @0: Text;
    delay @1: Float64;
    values @2: List(Float64)=[0.0];
    states @3: List(Bool)=[false];
    error @4: Int16 = 0;
    et    @5: Float32 = 0.0;
}

struct DeviceEvent {
    event @0: Text;
    command @1: Text;
    names @2: List(Text);
    values @3: List(Float64);
    units @4: List(Text) = ["None"];
    device @5: Text = "RIAPS";
    error @6: Int16 = 0;
    et    @7: Float32 = 0.0;
}