// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: ResponseFormat.capnp

#ifndef CAPNP_INCLUDED_ac3fa4cf20cb4a08_
#define CAPNP_INCLUDED_ac3fa4cf20cb4a08_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5003
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(e627651ce2e48837);

}  // namespace schemas
}  // namespace capnp

namespace riapsModbusUART {

struct ResponseFormat {
  ResponseFormat() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e627651ce2e48837, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class ResponseFormat::Reader {
public:
  typedef ResponseFormat Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::int16_t getCommandType() const;

  inline  ::int16_t getRegisterAddress() const;

  inline  ::int16_t getNumberOfRegs() const;

  inline bool hasValues() const;
  inline  ::capnp::List< ::int16_t>::Reader getValues() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ResponseFormat::Builder {
public:
  typedef ResponseFormat Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int16_t getCommandType();
  inline void setCommandType( ::int16_t value);

  inline  ::int16_t getRegisterAddress();
  inline void setRegisterAddress( ::int16_t value);

  inline  ::int16_t getNumberOfRegs();
  inline void setNumberOfRegs( ::int16_t value);

  inline bool hasValues();
  inline  ::capnp::List< ::int16_t>::Builder getValues();
  inline void setValues( ::capnp::List< ::int16_t>::Reader value);
  inline void setValues(::kj::ArrayPtr<const  ::int16_t> value);
  inline  ::capnp::List< ::int16_t>::Builder initValues(unsigned int size);
  inline void adoptValues(::capnp::Orphan< ::capnp::List< ::int16_t>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::int16_t>> disownValues();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ResponseFormat::Pipeline {
public:
  typedef ResponseFormat Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::int16_t ResponseFormat::Reader::getCommandType() const {
  return _reader.getDataField< ::int16_t>(
      0 * ::capnp::ELEMENTS);
}

inline  ::int16_t ResponseFormat::Builder::getCommandType() {
  return _builder.getDataField< ::int16_t>(
      0 * ::capnp::ELEMENTS);
}
inline void ResponseFormat::Builder::setCommandType( ::int16_t value) {
  _builder.setDataField< ::int16_t>(
      0 * ::capnp::ELEMENTS, value);
}

inline  ::int16_t ResponseFormat::Reader::getRegisterAddress() const {
  return _reader.getDataField< ::int16_t>(
      1 * ::capnp::ELEMENTS);
}

inline  ::int16_t ResponseFormat::Builder::getRegisterAddress() {
  return _builder.getDataField< ::int16_t>(
      1 * ::capnp::ELEMENTS);
}
inline void ResponseFormat::Builder::setRegisterAddress( ::int16_t value) {
  _builder.setDataField< ::int16_t>(
      1 * ::capnp::ELEMENTS, value);
}

inline  ::int16_t ResponseFormat::Reader::getNumberOfRegs() const {
  return _reader.getDataField< ::int16_t>(
      2 * ::capnp::ELEMENTS);
}

inline  ::int16_t ResponseFormat::Builder::getNumberOfRegs() {
  return _builder.getDataField< ::int16_t>(
      2 * ::capnp::ELEMENTS);
}
inline void ResponseFormat::Builder::setNumberOfRegs( ::int16_t value) {
  _builder.setDataField< ::int16_t>(
      2 * ::capnp::ELEMENTS, value);
}

inline bool ResponseFormat::Reader::hasValues() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool ResponseFormat::Builder::hasValues() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::int16_t>::Reader ResponseFormat::Reader::getValues() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::List< ::int16_t>::Builder ResponseFormat::Builder::getValues() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void ResponseFormat::Builder::setValues( ::capnp::List< ::int16_t>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline void ResponseFormat::Builder::setValues(::kj::ArrayPtr<const  ::int16_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::int16_t>::Builder ResponseFormat::Builder::initValues(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void ResponseFormat::Builder::adoptValues(
    ::capnp::Orphan< ::capnp::List< ::int16_t>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::int16_t>> ResponseFormat::Builder::disownValues() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::int16_t>>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

}  // namespace

#endif  // CAPNP_INCLUDED_ac3fa4cf20cb4a08_
