/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.ui;

import edu.vanderbilt.riaps.ui.AbstractDatatypesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DatatypesUiModule extends AbstractDatatypesUiModule {
  public DatatypesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
