RIAPSHOME=/usr/local/riaps
RIAPSAPPS=/home/riaps/riaps_apps
LD_LIBRARY_PATH=/usr/local/lib
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# IP address or hostname of the RIAPS controller node.
# Override this on each node to match the actual controller address.
RIAPS_CTRL_NODE=localhost
