/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.tests;

import com.google.inject.Inject;
import edu.vanderbilt.riaps.datatypes.Mdodel;
import edu.vanderbilt.riaps.tests.DatatypesInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DatatypesInjectorProvider.class)
@SuppressWarnings("all")
public class DatatypesParsingTest {
  @Inject
  private ParseHelper<Mdodel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext! ");
      _builder.newLine();
      final Mdodel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
