/*
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DatatypesStandaloneSetup extends DatatypesStandaloneSetupGenerated {

	def static void doSetup() {
		new DatatypesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
