pkill -SIGKILL xterm
pkill -SIGKILL riaps_ctrl
pkill -SIGKILL rpyc_registry.py
pkill -SIGKILL redis-server
pkill -SIGKILL riaps_disco
pkill -SIGKILL riaps_devm
pkill -SIGKILL gridlabd
pkill -SIGKILL gridlabd.bin 
pkill -SIGKILL python3 
