/**
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.ui.contentassist;

import edu.vanderbilt.riaps.ui.contentassist.AbstractDatatypesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DatatypesProposalProvider extends AbstractDatatypesProposalProvider {
}
