//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_COMPUTATIONALCOMPONENT_H
#define RIAPS_FW_COMPUTATIONALCOMPONENT_H

#include "ComputationalComponentBase.h"

namespace riapsmodbuscreqrepuart {
   namespace components {
      
      class ComputationalComponent : public ComputationalComponentBase {
         
         public:
         
         ComputationalComponent(_component_conf_j &config, riaps::Actor &actor);
         
         virtual void OnClock(riaps::ports::PortBase *port);
         
         
         
         virtual void OnOneShotTimer(const std::string& timerid);
         
         virtual ~ComputationalComponent();
         
      };
   }
}

extern "C" riaps::ComponentBase* create_component(_component_conf_j&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_COMPUTATIONALCOMPONENT_H
