//
// Auto-generated by edu.vanderbilt.riaps.generator.ComponenetGenerator.xtend
//
#ifndef RIAPS_FW_LOGGER_H
#define RIAPS_FW_LOGGER_H

#include "LoggerBase.h"

namespace riapsmodbuscreqrepuart {
   namespace components {
      
      class Logger : public LoggerBase {
         
         public:
         
         Logger(_component_conf_j &config, riaps::Actor &actor);
         
         virtual void OnRx_modbusData(const riapsModbusUART::LogData::Reader &message,
         riaps::ports::PortBase *port);
         
         virtual void OnOneShotTimer(const std::string& timerid);
         
         virtual ~Logger();
         
      };
   }
}

extern "C" riaps::ComponentBase* create_component(_component_conf_j&, riaps::Actor& actor);
extern "C" void destroy_component(riaps::ComponentBase*);


#endif //RIAPS_FW_LOGGER_H
