/*
 * generated by Xtext 2.10.0
 */
package edu.vanderbilt.riaps.ui;

import com.google.inject.Injector;
import edu.vanderbilt.riaps.datatypes.ui.internal.DatatypesActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DatatypesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DatatypesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DatatypesActivator.getInstance().getInjector(DatatypesActivator.EDU_VANDERBILT_RIAPS_DATATYPES);
	}
	
}
